basePath: https://base
info:
  contact:
    email: user@all.users
  description: API for users
  title: User API
  version: @project.version@
paths:
  /sample/v1/users/{id}:
    get:
      description: Retrieve a user
      operationId: getUser
      parameters:
        - description: User ID
          in: path
          name: id
          required: true
          type: string
      responses:
        200:
          description: ok
          schema:
            $ref: "#/definitions/User"
        400:
          description: Invalid request
        404:
          description: User not found
        500:
          description: Internal error
      summary: Retrieve a user.
      tags:
        - user
  /sample/v1/users:
    get:
      description: Get all users
      operationId: getUsers
      responses:
        200:
          description: ok
          schema:
            $ref: "#/definitions/Users"
        400:
          description: invalid request
        500:
          description: internal error
      summary: Get all users.
      tags:
        - user
    post:
      description: Add a new user
      operationId: postUser
      parameters:
        - description: the user to be added
          in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: ok
        400:
          description: invalid request
        500:
          description: internal error
      summary: Add a new user.
      tags:
        - user
swagger: 2.0
tags:
  - description: user
    name: user
tsModels:
  - ../../model/ts/user.ts
